PPP: Change data argument in sio_write to const
To fix the build after ppp_output_cb started taking it as const in
commit 56c2f3a79a52e7e01a29fec47cc6015e8a7b513c.

Fixes this failure:
../contrib/examples/ppp/pppos_example.c: In function ‘ppp_output_cb’:
../contrib/examples/ppp/pppos_example.c:163:29: error: cast discards ‘const’ qualifier from pointer target type [-Werror=cast-qual]
   return sio_write(ppp_sio, (u8_t*)data, len);
                             ^